project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - "files/"

execute:
  # Re-render only when source changes
  freeze: auto

website:
  title: "`bayesf22` Notebook"
  
  favicon: "/files/favicon.png"
  
  repo-url: "https://github.com/andrewheiss/bayesf22-notebook"
  repo-actions: [edit, issue]
  
  page-navigation: true
  
  navbar:
    pinned: true
    background: "#931e18"
    right:
      - text: "Main bayesf22 class"
        href: https://bayesf22.classes.andrewheiss.com/
      - text: "Statistical Rethinking"
        file: rethinking/index.qmd
      - text: "Bayes Rules!"
        file: bayes-rules/index.qmd
      - icon: github
        href: "https://github.com/andrewheiss/bayesf22-notebook"
        aria-label: GitHub
  
  sidebar:
    - title: "Statistical Rethinking"
      style: "floating"
      contents: 
        - rethinking/index.qmd
        - section: "3: Sampling and grid approximation"
          contents:
            - rethinking/03-chapter.qmd
            - rethinking/03-practice.qmd
    
    - title: "Bayes Rules!"
      contents:
        - bayes-rules/index.qmd
        - section: "2: Bayes' rule"
          contents:
            - bayes-rules/02-chapter.qmd
        - section: "3: The Beta-Binomial Bayesian model"
          contents:
            - bayes-rules/03-chapter.qmd

format:
  html:
    shift-heading-level-by: 1
    theme:
      - litera
      - html/custom.scss
    highlight-style: monokai
    toc: true
    toc-depth: 4
    retina: 3
    fig-width: 7
    fig-height: 4.5
    fig-align: center
    knitr:
      opts_chunk:
        collapse: true
