project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - "files/"

execute:
  # Re-render only when source changes
  freeze: auto

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "`bayesf22` Notebook"
  
  favicon: "/files/favicon.png"
  
  repo-url: "https://github.com/andrewheiss/bayesf22-notebook"
  repo-actions: [edit, issue]
  
  page-navigation: true
  
  navbar:
    pinned: true
    background: "#931e18"
    right:
      - text: "Main bayesf22 class"
        href: https://bayesf22.classes.andrewheiss.com/
      - text: "Statistical Rethinking"
        file: rethinking/index.qmd
      - text: "Bayes Rules!"
        file: bayes-rules/index.qmd
      - icon: github
        href: "https://github.com/andrewheiss/bayesf22-notebook"
        aria-label: GitHub
  
  sidebar:
    - title: "Statistical Rethinking"
      style: "floating"
      contents: 
        - rethinking/index.qmd
        - section: "Week 1:<br>Bayesian inference"
          contents:
            - rethinking/03-chapter.qmd
            - rethinking/03-practice.qmd
        - section: "Week 2:<br>Linear models & causal inference"
          contents:
            - rethinking/03-video.qmd
            - rethinking/04-video.qmd
        - section: "Week 3:<br>Causes, confounds, and colliders"
          contents:
            - rethinking/05-video.qmd
            - rethinking/06-video.qmd
        - section: "Week 4:<br>Overfitting & interactions"
          contents:
            - rethinking/07-video.qmd
        - section: "Week 5:<br>MCMC & generalized linear models"
        - section: "Week 6:<br>Integers & other monsters"
          contents: 
            - rethinking/10-video.qmd
        - section: "Week 7:<br>Multilevel models I"
        - section: "Week 8:<br>Multilevel models II"
        - section: "Week 9:<br>Measurement & missingness"
        - section: "Week 10:<br>Generalized linear madness"
    
    - title: "Bayes Rules!"
      contents:
        - bayes-rules/index.qmd
        - section: "2: Bayes' rule"
          contents:
            - bayes-rules/02-chapter.qmd
        - section: "3: The Beta-Binomial Bayesian model"
          contents:
            - bayes-rules/03-chapter.qmd
        - section: "4: Balance and sequentiality"
          contents:
            - bayes-rules/04-practice.qmd
        - section: "5: Conjugate families"
          contents:
            - bayes-rules/05-chapter.qmd
            - bayes-rules/05-practice.qmd
        - section: "6: Approximating the posterior"
          contents:
            - bayes-rules/06-chapter.qmd
        - section: "7: MCMC under the hood"
          contents:
            - bayes-rules/07-chapter.qmd
        - section: "8: Posterior inference and prediction"
          contents:
            - bayes-rules/08-chapter.qmd
        - section: "9: Simple normal regression"
          contents:
            - bayes-rules/09-chapter.qmd
        - section: "10: Evaluating regression models"
          contents:
            - bayes-rules/10-chapter.qmd
        - section: "11: Extending the normal regression model"
          contents:
            - bayes-rules/11-chapter.qmd
        - section: "12: Poisson and negative binomial regression"
          contents:
            - bayes-rules/12-chapter.qmd
        - section: "13: Logistic regression"
          contents:
            - bayes-rules/13-chapter.qmd
        - section: "15: Hierarchical models are exciting"
          contents:
            - bayes-rules/15-chapter.qmd
        - section: "16: Hierarchical models without predictors"
          contents:
            - bayes-rules/16-chapter.qmd
        - section: "17: Hierarchical models with predictors"
          contents:
            - bayes-rules/17-chapter.qmd

format:
  html:
    shift-heading-level-by: 1
    theme:
      - litera
      - html/custom.scss
    highlight-style: monokai
    toc: true
    toc-depth: 4
    retina: 3
    fig-width: 7
    fig-height: 4.5
    fig-align: center
    knitr:
      opts_chunk:
        collapse: true
